name: Testing

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Cache the installation of Poetry itself, e.g. the next step. This prevents the workflow
      # from installing Poetry every time which can be slow
      - name: Cache Poetry install
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-1.4.2

      # Install Poetry
      - uses: snok/install-poetry@v1
        with:
          version: 1.4.2
          virtualenvs-create: true
          virtualenvs-in-project: true

      # Cache your dependencies
      - name: Cache deps
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}

      # Install dependencies
      - run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'

      # Now install _your_ project
      - run: poetry install --no-interaction

      # And finally run tests
      # Need to grab the IDD file for the tests to run, and we don't want to include it in the repo, so we download it here
      - name: Download Energy+ IDD file
        run: wget https://raw.githubusercontent.com/NREL/EnergyPlus/2ad5b542c761abde2179225b08ce7af0b94a5d3b/idd/versions/V8-9-0-Energy%2B.idd -O test.idd

      - name: Run Tests
        env:
          IDD_FILE: ${{ github.workspace }}/test.idd
        run: poetry run python -m unittest -v

      - name: Build Docs
        run: poetry run sphinx-build -n -W -b html docs/source docs/build/html
